site_name: Parth Pandhare
site_url: https://sitename.example


theme:
  name: material
  # font:
    # text: 
    # code:
  icon:
    logo: fontawesome/solid/laptop-code # check: https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/
  features:
    - navigation.footer
  palette:
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: cyan
      accent: deep purple
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: cyan
      accent: deep orange


markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details


extra:
  social:
    - icon: simple/youtube
      link: https://www.youtube.com/@parthpandhare7916
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/parth-pandhare/


copyright: Copyright &copy; 2025 Parth Pandhare